### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [cibernox/PyPoolstation#1]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

Thanks

**Comment by cibernox** [comment]
You mean git tags? If so, I just created a tag for 0.4.0: https://github.com/cibernox/PyPoolstation/tags

**Comment by cibernox** [comment]
I wasn't aware creating git tags was necessary when a library was published in pypi already.

**Comment by fabaff** [comment]
Thanks. Yes, I was talking about git tags.

> I wasn't aware creating git tags was necessary when a library was published in pypi already.

It's more a "thing" for creating packages for distributions or people who don't want to depend on a third-party content delivery mechanism/repos. Often the tests or the LICENSE file is no part of the source that is published on PyPI. E.g., for Fedora it's needed to ship the license file as part of the package.
