### ISSUE TITLE
Error when parsing pool temperature

### ISSUE THREAD

**Issue by arturonaredo** [cibernox/PyPoolstation#2]
Hi @cibernox,

first of all thanks for your custom component! 

I have tested with the demo@demo.com / demo auth settings that are available at https://poolstation.net/ and works great, fetches everything right, but with the installation I have I'm getting an error in this line :  

https://github.com/cibernox/PyPoolstation/blob/7b56ed4d5fe207ea1ea1359e187242be3fe3b4aa/pypoolstation/__init__.py#L78

And the following error:

```
Unexpected error fetching poolstation-None data: could not convert string to float: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 190, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/poolstation/__init__.py", line 81, in _async_update_data
    await self._device.sync_info()
  File "/usr/local/lib/python3.9/site-packages/pypoolstation/__init__.py", line 78, in sync_info
    self.temperature = float(info["vars"]["ta"][0:-1])  # in °C
ValueError: could not convert string to float: ''
```

I have tried to fix it but I'm not really sure how to debug the value that the API is retrieving since the pypoolstation package is embeded in site-packages and not directly installed like custom component hence not editable. 

Could you please help me to take a look? I don't mind to make a PR after and contribute. 

Regards from Coruña!

**Comment by cibernox** [comment]
I need to resume working on this integration. Since I didn’t use the pool during winter I didn’t care. There’s an unsolved issue we’re it doesn’t login again when the session expires. 

I’ll try again when I can find some time. 

Regards from Oleiros!

**Comment by arturonaredo** [comment]
@cibernox ,

Its getting hot in Oleiros and Coruña... could you priorize this fix ? Would be so nice to have this integration working. 

Regards

**Comment by cibernox** [comment]
I started working on this, but since I haven't done python in a long long time I haven't done much. I did spawn a new home assistant docker image with this integration and it worked well using the demo account. Temperatures seem to be numbers and parse just fine.

What are you receiving as temperature? An empty string?

**Comment by arturonaredo** [comment]
Hi @cibernox ,

This is the error I got:

Unexpected error fetching poolstation-None data: could not convert string to float: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/poolstation/__init__.py", line 101, in _async_update_data
    await self._device.sync_info()
  File "/usr/local/lib/python3.10/site-packages/pypoolstation/__init__.py", line 106, in sync_info
    self.temperature = float(info["vars"][API_SIGNS["temperature"]][0:-1])  # in °C
ValueError: could not convert string to float: ''

Do you have a tip to do a postman and get what the api is exactly answering? So I could provide you a test json.

Thanks. 
Arturo.

**Comment by cibernox** [comment]
I published a new version that hopefully should fix this. IDK why the temperature would be missing from the payload, but since reality seems to prove that sometimes it is, I accounted for it.
