### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by emcepe** [cibernox/PyPoolstation#3]
Hello cibernox,

glad I found this project. I tried weeks to get a working request chain with FHEM and httpmod w/o success.

after days of trial & error I was able to get some values from my Pool Station - but I do miss some values.

This is the current output (prettified with jq)

````
{`
  "id": 1234,
  "alias": "Elite Connect LS",
  "temperature": 26.9,
  "salt_concentration": 0,
  "current_ph": 7.8,
  "target_ph": 7.4,
  "percentage_electrolysis": 0,
  "target_percentage_electrolysis": 100
}
````
if I look at the poolstation App or via poolstation.net Website, I'll see "Clmv" and also the "Redox (ORP)" value.

Is it possible to add those values to the output? :)

It would be nice also if you can make a more clear howto. I was not able to get it up and running until I found [testing_snippets.txt](https://github.com/cibernox/PyPoolstation/blob/main/testing_snippets.txt) - I am new to Python.

I like to know how to start/stop the relays for example or set target ph, target ORP, target ClmV, disable/enable the fuse for auto-pH regulation and so on.

Many thanks.

**Comment by cibernox** [comment]
I just update the library adding support for ORP and Chlorine PPM. Now I have to update the home assistant integration to support those, but it should be rather mechanical as they should work just like the PH sensor/target.

**Comment by emcepe** [comment]
thank you!

**Comment by cibernox** [comment]
@emcepe I updated the HACS integration yesterday too. Hopefully it works.
If you can please take special attention to wether the integration creates sensors and target for ORP and Free Chloline. I tried to make the integration smart enough to not create them if you don't have ORP/Chlorine sensor. In your case I think it should create `current ORP` and `target ORP` but not create anything for the free chlorine.

**Comment by emcepe** [comment]
I don't use HACS, I just use the stuff from [testing_snippets.txt](https://github.com/cibernox/PyPoolstation/blob/main/testing_snippets.txt) which you removed for whatever reason.

I don't have a sensor for clppm so it's None. For piping through jq it has to be "None" instead of just None because: Invalid numeric literal.

My current output after my local changes:

```
{
  "id": 1234,
  "alias": "Elite Connect LS",
  "temperature": 28.5,
  "salt_concentration": 1.9,
  "ph_current": 7.4,
  "ph_target": 7.4,
  "clmv_current": 717,
  "clmv_target": 777,
  "clppm_current": "None",
  "clppm_target": "None",
  "electrolysis_current": 100,
  "electrolysis_target": 100
}
```
I use this json output to get the data into FHEM.

**Comment by cibernox** [comment]
@emcepe oh, I added it to gitignore because I often use my real username and password and I didn't want to commit those in git by mistake.
I assumed you were using this with the home assistant integration. In that case what I said doesn't apply. I have never heard of FHEM before!
